cw: Source/main.cpp Source/BinTreeNode.cpp Source/BinTreeNode.h Source/functions.cpp Source/functions.h
	g++ -std=c++17 Source/main.cpp Source/BinTreeNode.cpp Source/functions.cpp -o cw

run_tests:
	./test_script.sh

clean:
	rm  cw
