#!/bin/bash

arg1=$(cat Tests/test1.txt)
echo "Test 1:"
echo "argument = $arg1"
touch result1.txt
./lab1 ./Tests/test1.txt > result1.txt
cat result1.txt

echo -e "\nTest 2:"
arg2=$(cat Tests/test2.txt)
echo "argument = $arg2"
touch result2.txt
./lab1 ./Tests/test2.txt > result2.txt
cat result2.txt

echo -e "\nTest 3:"
arg3=$(cat Tests/test3.txt)
echo "argument = $arg3"
touch result3.txt
./lab1 ./Tests/test3.txt > result3.txt
cat result3.txt

echo -e "\nTest 4:"
arg4=$(cat Tests/test4.txt)
echo "argument = $arg4"
touch result4.txt
./lab1 ./Tests/test4.txt > result4.txt
cat result4.txt

echo -e "\nTest 5:"
arg5=$(cat Tests/test5.txt)
echo "argument = $arg5"
touch result5.txt
./lab1 ./Tests/test5.txt > result5.txt
cat result5.txt