#!/bin/bash

arg1=$(cat Tests/test1.txt)
echo -e "_______________________________________\n"
echo -e "Test 1:\n"
echo "argument 1 = $arg1"
echo
./lab3 ./Tests/test1.txt

arg1=$(cat Tests/test2.txt)
echo -e "_______________________________________\n"
echo -e "Test 2:\n"
echo "argument 1 = $arg1"
echo
./lab3 ./Tests/test2.txt

arg1=$(cat Tests/test3.txt)
echo -e "_______________________________________\n"
echo -e "Test 3:\n"
echo "argument 1 = $arg1"
echo
./lab3 ./Tests/test3.txt

arg1=$(cat Tests/test4.txt)
echo -e "_______________________________________\n"
echo -e "Test 4:\n"
echo "argument 1 = $arg1"
echo
./lab3 ./Tests/test4.txt

arg1=$(cat Tests/test5.txt)
echo -e "_______________________________________\n"
echo -e "Test 5:\n"
echo "argument 1 = $arg1"
echo
./lab3 ./Tests/test5.txt
echo -e "_______________________________________\n"