#!/bin/bash
 
printf "\nRunning tests...\n\n"
for n in {1..7}
do
    ./lab2 < "./Tests/tests/test$n.txt" > "./Tests/out/out$n.txt"
    printf "Test$n: "
    printf "\n"
    cat "./Tests/tests/test$n.txt"
    if diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines "./Tests/true_results/true_out$n.txt" "./Tests/out/out$n.txt"; 
    then
	echo "correct"
    else
	echo "incorrec!"
    fi
    printf "Reference result:\n"
    cat "./Tests/true_results/true_out$n.txt"
    printf "Result of a programm:\n"
    cat "./Tests/out/out$n.txt"
    printf "\n"  
done
rm ./Tests/out/out*
