lab5:
	g++ -std=c++17 ./Source/main.cpp -o lab5

run_tests:
	./test_script.sh	

clean:
	cp -r Source Tests test_script.sh Makefile Atamanov_Sergey_lb5.pdf ..
	rm -rf *
	cp -r ../Source ../Tests ../test_script.sh ../Makefile ../Atamanov_Sergey_lb5.pdf ../lab5
	rm -rf ../Source ../Tests ../test_script.sh ../Makefile ../Atamanov_Sergey_lb5.pdf
