#!/bin/bash

arg1=$(cat Tests/test1-1.txt)
arg2=$(cat Tests/test1-2.txt)
echo -e "_______________________________________\n"
echo -e "Test 1:\n"
echo "    argument 1 ="
echo "$arg1"
echo "    argument 2 ="
echo -e "$arg2\n"
./lab2 ./Tests/test1-1.txt ./Tests/test1-2.txt

arg1=$(cat Tests/test2-1.txt)
arg2=$(cat Tests/test2-2.txt)
echo -e "_______________________________________\n"
echo -e "Test 2:\n"
echo "    argument 1 ="
echo "$arg1"
echo "    argument 2 ="
echo -e "$arg2\n"
./lab2 ./Tests/test2-1.txt ./Tests/test2-2.txt

arg1=$(cat Tests/test3-1.txt)
arg2=$(cat Tests/test3-2.txt)
echo -e "_______________________________________\n"
echo -e "Test 3:\n"
echo "    argument 1 ="
echo "$arg1"
echo "    argument 2 ="
echo -e "$arg2\n"
./lab2 ./Tests/test3-1.txt ./Tests/test3-2.txt

arg1=$(cat Tests/test4-1.txt)
arg2=$(cat Tests/test4-2.txt)
echo -e "_______________________________________\n"
echo -e "Test 4:\n"
echo "    argument 1 ="
echo "$arg1"
echo "    argument 2 ="
echo -e "$arg2\n"
./lab2 ./Tests/test4-1.txt ./Tests/test4-2.txt

arg1=$(cat Tests/test5-1.txt)
arg2=$(cat Tests/test5-2.txt)
echo -e "_______________________________________\n"
echo -e "Test 5:\n"
echo "    argument 1 ="
echo "$arg1"
echo "    argument 2 ="
echo -e "$arg2\n"
./lab2 ./Tests/test5-1.txt ./Tests/test5-2.txt
echo -e "_______________________________________\n"